<?php

namespace App\Services;

use App\Models\Invoice;
use App\Models\Service;
use Carbon\Carbon;
use Illuminate\Support\Collection;

class BillingService
{
    /**
     * Default billing cycle in days (monthly billing).
     */
    protected int $billingCycleDays;

    /**
     * Create a new BillingService instance.
     */
    public function __construct()
    {
        // Get billing cycle from config, default to 30 days (monthly)
        $this->billingCycleDays = config('billing.cycle_days', 30);
    }

    /**
     * Generate an invoice for a service.
     *
     * This method creates an invoice with:
     * - Amount calculated from the package price
     * - Due date set to (invoice_date + billing_cycle_days)
     * - Status set to 'unpaid'
     * - Invoice date set to today
     *
     * @param Service $service The service to generate invoice for
     * @return Invoice The generated invoice
     *
     * @throws \Exception If service doesn't have a package
     */
    public function generateInvoice(Service $service): Invoice
    {
        // Ensure service has a package
        if (!$service->package) {
            throw new \Exception("Service #{$service->id} does not have an associated package.");
        }

        // Get the invoice date (today)
        $invoiceDate = Carbon::today();

        // Calculate due date (invoice_date + billing_cycle_days)
        $dueDate = $invoiceDate->copy()->addDays($this->billingCycleDays);

        // Calculate amount from package price
        $amount = $service->package->price;

        // Create the invoice
        $invoice = Invoice::create([
            'service_id' => $service->id,
            'tenant_id' => $service->tenant_id,
            'amount' => $amount,
            'status' => 'unpaid',
            'invoice_date' => $invoiceDate,
            'due_date' => $dueDate,
            'payment_link' => null, // Will be generated by payment gateway integration
        ]);

        return $invoice;
    }

    /**
     * Generate invoices for all services that are due for billing.
     *
     * A service is due for billing if:
     * - Status is 'active'
     * - Expiry date is today or in the past
     *
     * @return Collection Collection of generated invoices
     */
    public function generateInvoicesForDueServices(): Collection
    {
        $today = Carbon::today();

        // Get all active services that are due for billing
        $dueServices = Service::where('status', 'active')
            ->whereDate('expiry_date', '<=', $today)
            ->with('package') // Eager load package to avoid N+1
            ->get();

        $generatedInvoices = collect();

        foreach ($dueServices as $service) {
            try {
                $invoice = $this->generateInvoice($service);
                $generatedInvoices->push($invoice);
            } catch (\Exception $e) {
                // Log error but continue processing other services
                \Log::error("Failed to generate invoice for service #{$service->id}: {$e->getMessage()}");
            }
        }

        return $generatedInvoices;
    }

    /**
     * Get all overdue invoices.
     *
     * An invoice is overdue if:
     * - Status is 'unpaid'
     * - Due date is in the past
     *
     * @return Collection Collection of overdue invoices
     */
    public function getOverdueInvoices(): Collection
    {
        return Invoice::where('status', 'unpaid')
            ->whereDate('due_date', '<', Carbon::today())
            ->with(['service.customer', 'service.package'])
            ->get();
    }

    /**
     * Calculate daily revenue for a specific date.
     *
     * @param Carbon $date The date to calculate revenue for
     * @return float Total revenue for the date
     */
    public function getDailyRevenue(Carbon $date): float
    {
        return Invoice::where('status', 'paid')
            ->whereDate('paid_at', $date)
            ->sum('amount');
    }

    /**
     * Calculate monthly revenue for a specific year and month.
     *
     * @param int $year The year
     * @param int $month The month (1-12)
     * @return float Total revenue for the month
     */
    public function getMonthlyRevenue(int $year, int $month): float
    {
        return Invoice::where('status', 'paid')
            ->whereYear('paid_at', $year)
            ->whereMonth('paid_at', $month)
            ->sum('amount');
    }

    /**
     * Generate a payment link for an invoice.
     *
     * @param Invoice $invoice The invoice to generate payment link for
     * @return string The payment link URL
     * @throws \Exception If payment link generation fails
     */
    public function generatePaymentLink(Invoice $invoice): string
    {
        $paymentGatewayService = new PaymentGatewayService();
        return $paymentGatewayService->createPaymentLink($invoice);
    }

    /**
     * Process a payment for an invoice.
     *
     * This is a placeholder method that will be implemented
     * when payment processing is added.
     *
     * @param Invoice $invoice The invoice to process payment for
     * @param array $paymentData Payment data from gateway
     * @return \App\Models\Payment The payment record
     */
    public function processPayment(Invoice $invoice, array $paymentData)
    {
        // TODO: Implement payment processing
        // This will be implemented in task 10.3
    }
}
